# Generated by Django 5.0.6 on 2024-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oakil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=78)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
